"""Constants for the Multi-Zone Mini-Split Thermostat integration."""

from homeassistant.components.climate import HVACMode

DOMAIN = "multizone_minisplit_thermostat"

PRESET_COMFORT = "comfort"
PRESET_ECO = "eco"
PRESET_FAILSAFE = "failsafe"
PRESETS = [PRESET_COMFORT, PRESET_ECO, PRESET_FAILSAFE]

HVAC_MODES = [HVACMode.HEAT, HVACMode.COOL]

CONF_ZONES = "zones"
CONF_ENTITY_ID = "entity_id"
CONF_PRESET_CONFIGS = "presets"
CONF_DEFAULT_PRESET = "default_preset"
CONF_PRIORITY = "priority"
CONF_TEMP_SENSOR_ENTITY_ID = "temp_sensor_entity_id"
CONF_HEAT_TEMP = "heat_temp"
CONF_COOL_TEMP = "cool_temp"
CONF_QUIET_MODE_ENTITY = "quiet_mode_entity"
CONF_DEBOUNCE_INTERVAL = "debounce_interval"
CONF_DEBOUNCE_THRESHOLD = "debounce_threshold"
CONF_MAX_ADJUSTMENT = "max_adjustment"

ATTR_ZONE_PRESETS = "zone_presets"
ATTR_ZONE_TARGET_TEMPS = "zone_target_temps"

SERVICE_SET_ZONE_PRESET = "set_zone_preset"
ATTR_ZONE = "zone"
ATTR_PRESET = "preset"

DEFAULT_HEAT_TEMP = 68.0
DEFAULT_COOL_TEMP = 74.0
DEFAULT_PRIORITY = 0
DEFAULT_DEBOUNCE_INTERVAL = 900
DEFAULT_DEBOUNCE_THRESHOLD = 0.5
DEFAULT_MAX_ADJUSTMENT = 3.0
MIN_MAX_ADJUSTMENT = 0.0
MAX_MAX_ADJUSTMENT = 5.0
STEP_MAX_ADJUSTMENT = 0.1

TEMPERATURE_TOLERANCE = 1.0
AUTOMATIC_MODE_COOLDOWN = 300
RECONCILE_INTERVAL = 60
RECONCILE_TEMP_TOLERANCE = 0.5
